<?php

use PostScripton\Money\Currency;

return array_merge(
    require 'popular_currencies.php',
    [
        [
            'full_name' => 'Afghan afghani',
            'name' => 'afghani',
            'iso_code' => 'AFN',
            'num_code' => '971',
            'symbol' => '؋',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Albanian lek',
            'name' => 'lek',
            'iso_code' => 'ALL',
            'num_code' => '008',
            'symbol' => 'L',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Armenian dram',
            'name' => 'dram',
            'iso_code' => 'AMD',
            'num_code' => '051',
            'symbol' => '֏',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Netherlands Antillean guilder',
            'name' => 'guilder',
            'iso_code' => 'ANG',
            'num_code' => '532',
            'symbol' => 'ƒ',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Angolan kwanza',
            'name' => 'kwanza',
            'iso_code' => 'AOA',
            'num_code' => '973',
            'symbol' => 'Kz',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Argentine peso',
            'name' => 'peso',
            'iso_code' => 'ARS',
            'num_code' => '032',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Aruban florin',
            'name' => 'florin',
            'iso_code' => 'AWG',
            'num_code' => '533',
            'symbol' => 'ƒ',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Azerbaijani manat',
            'name' => 'manat',
            'iso_code' => 'AZN',
            'num_code' => '944',
            'symbol' => '₼',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Bosnia and Herzegovina convertible mark',
            'name' => 'convertible mark',
            'iso_code' => 'BAM',
            'num_code' => '977',
            'symbol' => 'KM',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Barbados dollar',
            'name' => 'dollar',
            'iso_code' => 'BBD',
            'num_code' => '052',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Bangladeshi taka',
            'name' => 'taka',
            'iso_code' => 'BDT',
            'num_code' => '050',
            'symbol' => '৳',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Bulgarian lev',
            'name' => 'lev',
            'iso_code' => 'BGN',
            'num_code' => '975',
            'symbol' => 'лв.',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Bahraini dinar',
            'name' => 'dinar',
            'iso_code' => 'BHD',
            'num_code' => '048',
            'symbol' => '.د.ب',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Burundian franc',
            'name' => 'franc',
            'iso_code' => 'BIF',
            'num_code' => '108',
            'symbol' => 'Fr',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Bermudian dollar',
            'name' => 'dollar',
            'iso_code' => 'BMD',
            'num_code' => '060',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Brunei dollar',
            'name' => 'dollar',
            'iso_code' => 'BND',
            'num_code' => '096',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Boliviano boliviano',
            'name' => 'boliviano',
            'iso_code' => 'BOB',
            'num_code' => '068',
            'symbol' => 'Bs.',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Bahamian dollar',
            'name' => 'dollar',
            'iso_code' => 'BSD',
            'num_code' => '044',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Bhutanese ngultrum',
            'name' => 'ngultrum',
            'iso_code' => 'BTN',
            'num_code' => '064',
            'symbol' => 'Nu.',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Botswana pula',
            'name' => 'pula',
            'iso_code' => 'BWP',
            'num_code' => '072',
            'symbol' => 'P',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Belarusian ruble',
            'name' => 'ruble',
            'iso_code' => 'BYN',
            'num_code' => '933',
            'symbol' => 'Br',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Belize dollar',
            'name' => 'dollar',
            'iso_code' => 'BZD',
            'num_code' => '084',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Congolese franc',
            'name' => 'franc',
            'iso_code' => 'CDF',
            'num_code' => '976',
            'symbol' => 'Fr',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Costa Rican colon',
            'name' => 'colon',
            'iso_code' => 'CRC',
            'num_code' => '188',
            'symbol' => '₡',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Cuban peso',
            'name' => 'peso',
            'iso_code' => 'CUP',
            'num_code' => '931',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Cape Verdean escudo',
            'name' => 'escudo',
            'iso_code' => 'CVE',
            'num_code' => '132',
            'symbol' => ['Esc', '$'],
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Djiboutian franc',
            'name' => 'franc',
            'iso_code' => 'DJF',
            'num_code' => '262',
            'symbol' => 'Fr',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Dominican peso',
            'name' => 'peso',
            'iso_code' => 'DOP',
            'num_code' => '214',
            'symbol' => 'RD$',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Algerian dinar',
            'name' => 'dinar',
            'iso_code' => 'DZD',
            'num_code' => '012',
            'symbol' => 'د.ج',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Egyptian pound',
            'name' => 'pound',
            'iso_code' => 'EGP',
            'num_code' => '818',
            'symbol' => ['£', 'ج.م'],
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Eritrean nakfa',
            'name' => 'nakfa',
            'iso_code' => 'ERN',
            'num_code' => '232',
            'symbol' => 'Nfk',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Ethiopian birr',
            'name' => 'birr',
            'iso_code' => 'ETB',
            'num_code' => '230',
            'symbol' => 'Br',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Fiji dollar',
            'name' => 'dollar',
            'iso_code' => 'FJD',
            'num_code' => '242',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Falkland Islands pound',
            'name' => 'pound',
            'iso_code' => 'FKP',
            'num_code' => '238',
            'symbol' => '£',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Georgian lari',
            'name' => 'lari',
            'iso_code' => 'GEL',
            'num_code' => '981',
            'symbol' => '₾',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Ghanaian cedi',
            'name' => 'cedi',
            'iso_code' => 'GHS',
            'num_code' => '936',
            'symbol' => '₵',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Gibraltar pound',
            'name' => 'pound',
            'iso_code' => 'GIP',
            'num_code' => '292',
            'symbol' => '£',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Gambian dalasi',
            'name' => 'dalasi',
            'iso_code' => 'GMD',
            'num_code' => '270',
            'symbol' => 'D',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Guinean franc',
            'name' => 'franc',
            'iso_code' => 'GNF',
            'num_code' => '324',
            'symbol' => 'Fr',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Guatemalan quetzal',
            'name' => 'quetzal',
            'iso_code' => 'GTQ',
            'num_code' => '320',
            'symbol' => 'Q',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Guyanese dollar',
            'name' => 'dollar',
            'iso_code' => 'GYD',
            'num_code' => '328',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Honduran lempira',
            'name' => 'lempira',
            'iso_code' => 'HNL',
            'num_code' => '340',
            'symbol' => 'L',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Croatian kuna',
            'name' => 'kuna',
            'iso_code' => 'HRK',
            'num_code' => '191',
            'symbol' => 'kn',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Haitian gourde',
            'name' => 'gourde',
            'iso_code' => 'HTG',
            'num_code' => '332',
            'symbol' => 'G',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Iraqi dinar',
            'name' => 'dinar',
            'iso_code' => 'IQD',
            'num_code' => '368',
            'symbol' => 'ع.د',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Iranian rial',
            'name' => 'rial',
            'iso_code' => 'IRR',
            'num_code' => '364',
            'symbol' => '﷼',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Icelandic króna',
            'name' => 'króna',
            'iso_code' => 'ISK',
            'num_code' => '352',
            'symbol' => 'kr',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Jamaican dollar',
            'name' => 'dollar',
            'iso_code' => 'JMD',
            'num_code' => '388',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Jordanian dinar',
            'name' => 'dinar',
            'iso_code' => 'JOD',
            'num_code' => '400',
            'symbol' => 'د.ا',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Kenyan shilling',
            'name' => 'shilling',
            'iso_code' => 'KES',
            'num_code' => '404',
            'symbol' => 'Sh',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Kyrgyzstani som',
            'name' => 'som',
            'iso_code' => 'KGS',
            'num_code' => '417',
            'symbol' => 'с',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Cambodian riel',
            'name' => 'riel',
            'iso_code' => 'KHR',
            'num_code' => '116',
            'symbol' => '៛',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Comoro franc',
            'name' => 'franc',
            'iso_code' => 'KMF',
            'num_code' => '174',
            'symbol' => 'Fr',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'North Korean won',
            'name' => 'won',
            'iso_code' => 'KPW',
            'num_code' => '408',
            'symbol' => '₩',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Kuwaiti dinar',
            'name' => 'dinar',
            'iso_code' => 'KWD',
            'num_code' => '414',
            'symbol' => 'د.ك',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Cayman Islands dollar',
            'name' => 'dollar',
            'iso_code' => 'KYD',
            'num_code' => '136',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Kazakhstani tenge',
            'name' => 'tenge',
            'iso_code' => 'KZT',
            'num_code' => '398',
            'symbol' => '₸',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Lao kip',
            'name' => 'kip',
            'iso_code' => 'LAK',
            'num_code' => '418',
            'symbol' => '₭',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Lebanese pound',
            'name' => 'pound',
            'iso_code' => 'LBP',
            'num_code' => '422',
            'symbol' => 'ل.ل',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Sri Lankan rupee',
            'name' => 'rupee',
            'iso_code' => 'LKR',
            'num_code' => '144',
            'symbol' => ['Rs', 'රු', 'ரூ'],
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Liberian dollar',
            'name' => 'dollar',
            'iso_code' => 'LRD',
            'num_code' => '430',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Lesotho loti',
            'name' => 'loti',
            'iso_code' => 'LSL',
            'num_code' => '426',
            'symbol' => 'L',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Libyan dinar',
            'name' => 'dinar',
            'iso_code' => 'LYD',
            'num_code' => '434',
            'symbol' => 'ل.د',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Moroccan dirham',
            'name' => 'dirham',
            'iso_code' => 'MAD',
            'num_code' => '504',
            'symbol' => 'د.م.',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Moldovan leu',
            'name' => 'leu',
            'iso_code' => 'MDL',
            'num_code' => '498',
            'symbol' => 'L',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Malagasy ariary',
            'name' => 'ariary',
            'iso_code' => 'MGA',
            'num_code' => '969',
            'symbol' => 'Ar',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Macedonian denar',
            'name' => 'denar',
            'iso_code' => 'MKD',
            'num_code' => '807',
            'symbol' => 'ден',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Myanmar kyat',
            'name' => 'kyat',
            'iso_code' => 'MMK',
            'num_code' => '104',
            'symbol' => 'Ks',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Mongolian tögrög',
            'name' => 'tögrög',
            'iso_code' => 'MNT',
            'num_code' => '496',
            'symbol' => '₮',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Macanese pataca',
            'name' => 'pataca',
            'iso_code' => 'MOP',
            'num_code' => '446',
            'symbol' => 'MOP$',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Mauritanian ouguiya',
            'name' => 'ouguiya',
            'iso_code' => 'MRU',
            'num_code' => '929',
            'symbol' => 'UM',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Mauritian rupee',
            'name' => 'rupee',
            'iso_code' => 'MUR',
            'num_code' => '480',
            'symbol' => '₨',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Maldivian rufiyaa',
            'name' => 'rufiyaa',
            'iso_code' => 'MVR',
            'num_code' => '462',
            'symbol' => '.ރ',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Malawian kwacha',
            'name' => 'kwacha',
            'iso_code' => 'MWK',
            'num_code' => '454',
            'symbol' => 'MK',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Mozambican metical',
            'name' => 'metical',
            'iso_code' => 'MZN',
            'num_code' => '943',
            'symbol' => 'MT',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Namibian dollar',
            'name' => 'dollar',
            'iso_code' => 'NAD',
            'num_code' => '516',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Nigerian naira',
            'name' => 'naira',
            'iso_code' => 'NGN',
            'num_code' => '566',
            'symbol' => '₦',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Nicaraguan córdoba',
            'name' => 'córdoba',
            'iso_code' => 'NIO',
            'num_code' => '558',
            'symbol' => 'C$',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Nepalese rupee',
            'name' => 'rupee',
            'iso_code' => 'NPR',
            'num_code' => '524',
            'symbol' => 'रू',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Omani rial',
            'name' => 'rial',
            'iso_code' => 'OMR',
            'num_code' => '512',
            'symbol' => 'ر.ع.',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Panamanian balboa',
            'name' => 'balboa',
            'iso_code' => 'PAB',
            'num_code' => '590',
            'symbol' => 'B/.',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Peruvian sol',
            'name' => 'sol',
            'iso_code' => 'PEN',
            'num_code' => '604',
            'symbol' => 'S/.',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Papua New Guinean kina',
            'name' => 'kina',
            'iso_code' => 'PGK',
            'num_code' => '598',
            'symbol' => 'K',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Pakistani rupee',
            'name' => 'rupee',
            'iso_code' => 'PKR',
            'num_code' => '586',
            'symbol' => '₨',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Paraguayan guaraní',
            'name' => 'guaraní',
            'iso_code' => 'PYG',
            'num_code' => '600',
            'symbol' => '₲',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Qatari riyal',
            'name' => 'riyal',
            'iso_code' => 'QAR',
            'num_code' => '634',
            'symbol' => 'ر.ق',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Serbian dinar',
            'name' => 'dinar',
            'iso_code' => 'RSD',
            'num_code' => '941',
            'symbol' => ['дин.', 'din.'],
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Rwandan franc',
            'name' => 'franc',
            'iso_code' => 'RWF',
            'num_code' => '646',
            'symbol' => 'Fr',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Solomon Islands dollar',
            'name' => 'dollar',
            'iso_code' => 'SBD',
            'num_code' => '090',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Seychelles rupee',
            'name' => 'rupee',
            'iso_code' => 'SCR',
            'num_code' => '690',
            'symbol' => '₨',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Sudanese pound',
            'name' => 'pound',
            'iso_code' => 'SDG',
            'num_code' => '938',
            'symbol' => 'ج.س.',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Saint Helena pound',
            'name' => 'pound',
            'iso_code' => 'SHP',
            'num_code' => '654',
            'symbol' => '£',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Sierra Leonean leone',
            'name' => 'leone',
            'iso_code' => 'SLL',
            'num_code' => '694',
            'symbol' => 'Le',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Somali shilling',
            'name' => 'shilling',
            'iso_code' => 'SOS',
            'num_code' => '706',
            'symbol' => 'Sh',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Surinamese dollar',
            'name' => 'dollar',
            'iso_code' => 'SRD',
            'num_code' => '968',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'South Sudanese pound',
            'name' => 'pound',
            'iso_code' => 'SSP',
            'num_code' => '728',
            'symbol' => '£',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'São Tomé and Príncipe dobra',
            'name' => 'dobra',
            'iso_code' => 'STN',
            'num_code' => '930',
            'symbol' => 'Db',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Syrian pound',
            'name' => 'pound',
            'iso_code' => 'SYP',
            'num_code' => '760',
            'symbol' => ['£', 'ل.س'],
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Swazi lilangeni',
            'name' => 'lilangeni',
            'iso_code' => 'SZL',
            'num_code' => '748',
            'symbol' => 'L',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Tajikistani somoni',
            'name' => 'somoni',
            'iso_code' => 'TJS',
            'num_code' => '972',
            'symbol' => 'SM',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Turkmenistan manat',
            'name' => 'manat',
            'iso_code' => 'TMT',
            'num_code' => '934',
            'symbol' => 'm',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Tunisian dinar',
            'name' => 'dinar',
            'iso_code' => 'TND',
            'num_code' => '788',
            'symbol' => 'د.ت',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Tongan paʻanga',
            'name' => 'paʻanga',
            'iso_code' => 'TOP',
            'num_code' => '776',
            'symbol' => 'T$',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Trinidad and Tobago dollar',
            'name' => 'dollar',
            'iso_code' => 'TTD',
            'num_code' => '780',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Tanzanian shilling',
            'name' => 'shilling',
            'iso_code' => 'TZS',
            'num_code' => '834',
            'symbol' => 'Sh',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Ukrainian hryvnia',
            'name' => 'hryvnia',
            'iso_code' => 'UAH',
            'num_code' => '980',
            'symbol' => '₴',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Ugandan shilling',
            'name' => 'shilling',
            'iso_code' => 'UGX',
            'num_code' => '800',
            'symbol' => 'Sh',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Uruguayan peso',
            'name' => 'peso',
            'iso_code' => 'UYU',
            'num_code' => '858',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'Uzbekistan soʻm',
            'name' => 'soʻm',
            'iso_code' => 'UZS',
            'num_code' => '860',
            'symbol' => ['so\'m', 'сўм'],
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Venezuelan bolívar soberano',
            'name' => 'bolívar soberano',
            'iso_code' => 'VES',
            'num_code' => '928',
            'symbol' => ['Bs.S.', 'Bs.'],
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Vietnamese đồng',
            'name' => 'đồng',
            'iso_code' => 'VND',
            'num_code' => '704',
            'symbol' => '₫',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Vanuatu vatu',
            'name' => 'vatu',
            'iso_code' => 'VUV',
            'num_code' => '548',
            'symbol' => 'Vt',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Samoan tala',
            'name' => 'tala',
            'iso_code' => 'WST',
            'num_code' => '882',
            'symbol' => 'T',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'CFA franc BEAC',
            'name' => 'franc',
            'iso_code' => 'XAF',
            'num_code' => '950',
            'symbol' => 'Fr',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'East Caribbean dollar',
            'name' => 'dollar',
            'iso_code' => 'XCD',
            'num_code' => '951',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
        [
            'full_name' => 'CFA franc BCEAO',
            'name' => 'franc',
            'iso_code' => 'XOF',
            'num_code' => '952',
            'symbol' => 'Fr',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Yemeni rial',
            'name' => 'rial',
            'iso_code' => 'YER',
            'num_code' => '886',
            'symbol' => '﷼',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Zambian kwacha',
            'name' => 'kwacha',
            'iso_code' => 'ZMW',
            'num_code' => '967',
            'symbol' => 'ZK',
            'position' => Currency::POSITION_END,
        ],
        [
            'full_name' => 'Zimbabwean dollar',
            'name' => 'dollar',
            'iso_code' => 'ZWL',
            'num_code' => '932',
            'symbol' => '$',
            'position' => Currency::POSITION_START,
        ],
    ]
);
